/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : string,
  'action' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'ipAddress' : string,
}
export interface Case {
  'id' : string,
  'status' : CaseStatus,
  'title' : string,
  'clientId' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'notes' : string,
  'investigatorId' : [] | [string],
}
export interface CaseFile {
  'id' : string,
  'createdAt' : bigint,
  'fileName' : string,
  'fileId' : string,
  'caseId' : string,
  'uploadedBy' : Principal,
}
export type CaseStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'pending' : null };
export interface Client {
  'id' : string,
  'kycFileId' : [] | [string],
  'userId' : string,
  'fullName' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Inquiry {
  'id' : string,
  'status' : InquiryStatus,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type InquiryStatus = { 'new' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface MediaFile {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'fileId' : string,
  'category' : string,
  'uploadedBy' : Principal,
}
export interface SiteSettings {
  'metaDescription' : string,
  'tagline' : string,
  'metaKeywords' : string,
  'themeColor' : string,
  'logoFileId' : [] | [string],
  'siteName' : string,
  'whatsappNumber' : string,
  'metaTitle' : string,
  'callNumber' : string,
}
export interface Staff {
  'id' : string,
  'userId' : string,
  'role' : string,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export interface User {
  'id' : string,
  'username' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebsiteContent {
  'footerTagline' : string,
  'faqItems' : string,
  'socialInstagram' : string,
  'heroStatSuccess' : string,
  'socialFacebook' : string,
  'heroCtaText' : string,
  'heroStatCases' : string,
  'teamMembers' : string,
  'agencyStory' : string,
  'servicesData' : string,
  'socialTwitter' : string,
  'heroSubheadline' : string,
  'contactEmail' : string,
  'legalDisclaimer' : string,
  'socialLinkedin' : string,
  'heroHeadline' : string,
  'contactAddress' : string,
  'contactPhone' : string,
  'heroStatYears' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    string
  >,
  'addNotesToCase' : ActorMethod<[string, string], undefined>,
  'addStaff' : ActorMethod<[string, string, string, string, string], string>,
  'approveInquiry' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignInvestigator' : ActorMethod<[string, string], undefined>,
  'attachFileToCase' : ActorMethod<[string, string, string], string>,
  'createCase' : ActorMethod<[string, string, string], string>,
  'createUser' : ActorMethod<[string, string, string, UserRole], string>,
  'deleteMediaRecord' : ActorMethod<[string], undefined>,
  'editClient' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    undefined
  >,
  'editStaff' : ActorMethod<
    [string, string, string, string, string, boolean],
    undefined
  >,
  'getAllCases' : ActorMethod<[], Array<Case>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getAllUsersSortedByEmail' : ActorMethod<[], Array<User>>,
  'getAllUsersSortedById' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCasesByClient' : ActorMethod<[string], Array<Case>>,
  'getClientDetails' : ActorMethod<[string], Client>,
  'getFilesForCase' : ActorMethod<[string], Array<CaseFile>>,
  'getLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getMediaByCategory' : ActorMethod<[string], Array<MediaFile>>,
  'getSettings' : ActorMethod<[], SiteSettings>,
  'getUser' : ActorMethod<[string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteContent' : ActorMethod<[], WebsiteContent>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logAction' : ActorMethod<[string, string], string>,
  'rejectInquiry' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMediaFile' : ActorMethod<[string, string, string], string>,
  'submitInquiry' : ActorMethod<[string, string, string, string], string>,
  'updateCaseStatus' : ActorMethod<[string, CaseStatus], undefined>,
  'updateSettings' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateUserStatus' : ActorMethod<[string, boolean], undefined>,
  'updateWebsiteContent' : ActorMethod<[WebsiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];