/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CaseStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const Case = IDL.Record({
  'id' : IDL.Text,
  'status' : CaseStatus,
  'title' : IDL.Text,
  'clientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'investigatorId' : IDL.Opt(IDL.Text),
});
export const Client = IDL.Record({
  'id' : IDL.Text,
  'kycFileId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const InquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : InquiryStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Staff = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CaseFile = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'fileName' : IDL.Text,
  'fileId' : IDL.Text,
  'caseId' : IDL.Text,
  'uploadedBy' : IDL.Principal,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'ipAddress' : IDL.Text,
});
export const MediaFile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'fileId' : IDL.Text,
  'category' : IDL.Text,
  'uploadedBy' : IDL.Principal,
});
export const SiteSettings = IDL.Record({
  'metaDescription' : IDL.Text,
  'tagline' : IDL.Text,
  'metaKeywords' : IDL.Text,
  'themeColor' : IDL.Text,
  'logoFileId' : IDL.Opt(IDL.Text),
  'siteName' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'metaTitle' : IDL.Text,
  'callNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'addNotesToCase' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addStaff' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'approveInquiry' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignInvestigator' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'attachFileToCase' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createCase' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Text],
      [],
    ),
  'deleteMediaRecord' : IDL.Func([IDL.Text], [], []),
  'editClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'editStaff' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getAllUsersSortedByEmail' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllUsersSortedById' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCasesByClient' : IDL.Func([IDL.Text], [IDL.Vec(Case)], ['query']),
  'getClientDetails' : IDL.Func([IDL.Text], [Client], ['query']),
  'getFilesForCase' : IDL.Func([IDL.Text], [IDL.Vec(CaseFile)], ['query']),
  'getLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getMediaByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MediaFile)], ['query']),
  'getSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUser' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logAction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'rejectInquiry' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMediaFile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateCaseStatus' : IDL.Func([IDL.Text, CaseStatus], [], []),
  'updateSettings' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateUserStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CaseStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Case = IDL.Record({
    'id' : IDL.Text,
    'status' : CaseStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'investigatorId' : IDL.Opt(IDL.Text),
  });
  const Client = IDL.Record({
    'id' : IDL.Text,
    'kycFileId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : InquiryStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Staff = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CaseFile = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'fileName' : IDL.Text,
    'fileId' : IDL.Text,
    'caseId' : IDL.Text,
    'uploadedBy' : IDL.Principal,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'ipAddress' : IDL.Text,
  });
  const MediaFile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'fileId' : IDL.Text,
    'category' : IDL.Text,
    'uploadedBy' : IDL.Principal,
  });
  const SiteSettings = IDL.Record({
    'metaDescription' : IDL.Text,
    'tagline' : IDL.Text,
    'metaKeywords' : IDL.Text,
    'themeColor' : IDL.Text,
    'logoFileId' : IDL.Opt(IDL.Text),
    'siteName' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'metaTitle' : IDL.Text,
    'callNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'addNotesToCase' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addStaff' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'approveInquiry' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignInvestigator' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'attachFileToCase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCase' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Text],
        [],
      ),
    'deleteMediaRecord' : IDL.Func([IDL.Text], [], []),
    'editClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'editStaff' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getAllUsersSortedByEmail' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllUsersSortedById' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCasesByClient' : IDL.Func([IDL.Text], [IDL.Vec(Case)], ['query']),
    'getClientDetails' : IDL.Func([IDL.Text], [Client], ['query']),
    'getFilesForCase' : IDL.Func([IDL.Text], [IDL.Vec(CaseFile)], ['query']),
    'getLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getMediaByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaFile)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUser' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logAction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'rejectInquiry' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMediaFile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateCaseStatus' : IDL.Func([IDL.Text, CaseStatus], [], []),
    'updateSettings' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateUserStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };